# Generated by Django 6.0 on 2026-01-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Quadra Poliesportiva, Auditório', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('capacidade', models.IntegerField(help_text='Capacidade máxima de pessoas')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque se o espaço estiver em reforma')),
            ],
            options={
                'verbose_name': 'Espaço',
                'verbose_name_plural': 'Espaços',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Ex: Futsal, Vôlei, Palestra', max_length=50)),
                ('data_inicio', models.DateTimeField(verbose_name='Início da Reserva')),
                ('data_fim', models.DateTimeField(verbose_name='Fim da Reserva')),
                ('detalhes', models.TextField(help_text='Como o espaço será usado?')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacao_admin', models.TextField(blank=True, null=True, verbose_name='Motivo da Negação/Obs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='glpi.espaco')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-created_at'],
            },
        ),
    ]
