# Generated by Django 6.0 on 2026-01-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glpi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='detalhes',
        ),
    ]
