# Generated by Django 6.0 on 2026-01-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glpi', '0002_remove_solicitacao_detalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='detalhes',
            field=models.TextField(blank=True, help_text='Como o espaço será usado?', null=True),
        ),
    ]
