# Generated by Django 6.0 on 2026-01-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glpi', '0003_solicitacao_detalhes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='detalhes',
            field=models.TextField(default='', help_text='Como o espaço será usado?'),
            preserve_default=False,
        ),
    ]
